fractaldotbox/ddevkit

apps/storybook/src/hooks/use-efp-api.ts, apps/storybook/src/stories/social-graph/NameAndFollowerCountBadge.stories.tsx, apps/storybook/src/stories/social-graph/NameAndFollowerCountBadge.tsx
=> add: NameAndFollowerCountBadge

apps/sample-socialfi/src/components/ui/alert.tsx, apps/storybook/src/components/ui/alert.tsx, apps/storybook/src/stories/filecoin/Uploader.tsx, apps/storybook/src/stories/filecoin/upload-dropzone.stories.tsx, apps/storybook/src/stories/filecoin/upload-dropzone.tsx, apps/storybook/src/stories/filecoin/upload.stories.tsx
- react-dropzone, shadcn based
- to integrate with backend api
=> add: file upload dropzone frame

apps/storybook/package.json, apps/storybook/src/stories/onchain-info/TokenChip.mdx, apps/storybook/src/stories/onchain-info/TokenChip.stories.tsx, apps/storybook/src/stories/onchain-info/TokenChip.tsx, apps/storybook/src/stories/onchain-info/__tests__/TokenChip.test.tsx, apps/storybook/test-setup.ts, apps/storybook/vite.config.ts, pnpm-lock.yaml
Fixes #11 
- Add `TokenChip` implementation with minimal deps based on https://onchainkit.xyz/token/token-chip
- Add example storybooks
- Added documentation and how-tos
=> feat: tokenchip implementation

apps/storybook/src/stories/identity/Address.stories.tsx, apps/storybook/src/stories/identity/Address.tsx, apps/storybook/src/stories/identity/__tests__/Address.test.tsx
Fixes #25
- Add copy icon and tooltip
- Add corresponding unit tests for address components
=> feat(address): address copying feature

apps/storybook/src/stories/filecoin/upload-dropzone.tsx, apps/storybook/src/stories/filecoin/upload.stories.tsx, apps/storybook/src/stories/transfer-button/transfer-button.stories.tsx, apps/storybook/src/stories/transfer-button/transfer-button.tsx
https://github.com/fractaldotbox/geist-dapp-kit/issues/15
=> feat: transfer button

.github/workflows/ci.yml, apps/storybook/src/stories/attestations/AttestationCard.tsx, apps/storybook/src/stories/attestations/AttestationFormEasSdk.stories.tsx
and fix eas import error
<sub><a href="https://huly.app/guest/geist?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQzMWMyYWQyZWY0Y2JjYzQ2ODY2ZmQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViZGVidWdnLWdlaXN0LTY3NDAzNjhlLTU0NTgxY2VhOWEtYmNhZDgwIn0.sghoIMAOeLARFLb1BzeCJl87SLYhBVoaFUQVXvs469M">Huly&reg;: <b>DAPPK-33</b></a></sub>
=> ci: add smoke test

.github/workflows/check.yml, .github/workflows/ci.yml, apps/storybook/package.json, package.json, pnpm-lock.yaml
The fleek deploy script finally works after fixing a stupid mistake. The biome check scripts also no longer checks for diffs only but instead check the entire repo.
<sub><a href="https://huly.app/guest/geist?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVlYjdjMWYxNDRmNTg1YWU0ZDVlODYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViZGVidWdnLWdlaXN0LTY3NDAzNjhlLTU0NTgxY2VhOWEtYmNhZDgwIn0.cL7viOgiw3UiUhHlEf_TQbW-gMBdiqTgj5YHuSOusLs">Huly&reg;: <b>DAPPK-52</b></a></sub>
=> Cleaned up CI scripts

apps/storybook/src/lib/blockscout/chain.ts, apps/storybook/src/lib/blockscout/url.ts, apps/storybook/src/lib/explorer/url.test.ts, apps/storybook/src/lib/explorer/url.ts, apps/storybook/src/lib/filecoin/url.ts, apps/storybook/src/stories/fixture.ts
decouple interface and avoid deps
not very satisfying with the layers will revisit once we got more examples
<sub><a href="https://huly.app/guest/geist?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzYwMDY1YWYxNDRmNTg1YWU0ZDgyZTkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViZGVidWdnLWdlaXN0LTY3NDAzNjhlLTU0NTgxY2VhOWEtYmNhZDgwIn0.mebYqD2_bM1NTQ3yHbxpM1LGWNLZtym2erGpt-nWA04">Huly&reg;: <b>DAPPK-55</b></a></sub>
=> chore: refactor blockexplorer url

.vscode/settings.json, apps/storybook/src/components/ui/toaster.tsx, apps/storybook/src/stories/filecoin/UploadForm.tsx, biome.json, packages/ui-react/src/components/attestations/attestation-badge.tsx, packages/ui-react/src/components/attestations/upload-attestation.tsx, packages/ui-react/src/components/data-table.tsx, packages/ui-react/src/components/privy/privy-login.tsx, packages/ui-react/src/components/shadcn/toaster.tsx, packages/ui-react/src/components/transactions/transaction-table-with-details.tsx, packages/ui-react/src/components/transactions/transaction-table.tsx, packages/ui-react/src/components/transfer/transfer-button.tsx, packages/ui-react/src/hooks/eas/use-upload-attestation.ts, packages/ui-react/src/lib/blockscout/data.fixture.ts, packages/ui-react/src/lib/wagmi-utils.ts
https://biomejs.dev/linter/rules/use-arrow-function/
- motivation is to encourage currying
- seems not applying to `export function`
- we want to aplpy for our own code while for shadcn/gql let it be
=> update: biome prefer arrow

apps/storybook/src/stories/token/YieldHistoricalChart.stories.tsx, packages/ui-react/src/components/token/yield-historical-chart.tsx
Fixes #77 and #74 (similar issues)
- Added Yield Historical Charts based on DeFiLlama PoolId
(can be enhanced with the defiLlama pool api)
=> feat(charts): yield historical charts based on defillama

apps/registry/src/parser.test.ts, apps/registry/src/parser.ts
`"#components/shadcn/tooltip"` in address-badge failed to get rewrite
=> fix: shadcn import rewrite

apps/storybook/src/stories/privy/privy-login.stories.tsx, packages/ui-react/src/components/privy/privy-login.tsx
Add privy logout since we cannot disconnect from WAGMI
=> feat: add privy logout

apps/storybook/src/stories/transactions/TransactionTable.stories.ts, apps/storybook/src/stories/transactions/TransactionTableWithDetails.stories.ts, packages/ui-react/src/components/data-table.tsx, packages/ui-react/src/components/transactions/transaction-table-with-details.tsx, packages/ui-react/src/components/transactions/transaction-table.tsx, packages/ui-react/src/lib/blockscout/api.int.test.ts, packages/ui-react/src/lib/blockscout/api.ts, packages/ui-react/src/lib/blockscout/data.fixture.ts
align to use `TransactionTable` with data loading
=> fix: TransactionTable naming convention and types

.github/workflows/storybook.yml, README.md, apps/docs/astro.config.mjs, apps/docs/src/content/docs/index.mdx, apps/docs/src/content/docs/intro/introduction.md, apps/storybook/.storybook/geist-theme.js, apps/storybook/src/stories/Configure.mdx
=> chore: dDevKit brand

CONTRIBUTING.md, apps/docs/astro.config.mjs, apps/docs/package.json, apps/docs/src/content/docs/guides/installation.md, apps/docs/src/content/docs/index.mdx, apps/docs/src/styles/global.css, apps/docs/tailwind.config.mjs, apps/storybook/.storybook/geist-theme.js, apps/storybook/src/stories/Configure.mdx, package.json, pnpm-lock.yaml
use tailwind v3 for starlight compatability
=> docs: tailwindcss

.github/actions/setup-node-pnpm/action.yml, apps/registry/src/build.mts, apps/registry/src/parser.ts, package.json, packages/ddev/README.md, packages/ddev/package.json, packages/ddev/src/utils/add-components.ts, packages/ui-react/src/components/passport/score-card.tsx, packages/ui-react/src/hooks/oso/use-timeseries.ts, pnpm-lock.yaml
for #42 testing `ddev` compatability
fix `pnpm` `10.7.1` to address `pnpm link` bug
- graphql path
- test `ddev`
=> fix: registry cli

apps/docs/astro.config.mjs
=> fix: update GitHub link in starlight configuration

.github/workflows/storybook.yml, apps/storybook/package.json, apps/storybook/src/stories/token/TokenPriceChart.stories.tsx, apps/storybook/src/stories/transactions/TransactionCard.stories.tsx, packages/ui-react/src/components/token/token-balance-chart.tsx, packages/ui-react/src/components/token/token-price-chart-with-feed.tsx, pnpm-lock.yaml
- added sample `TokenPriceChart`
=> add: story component test

apps/docs/astro.config.mjs, apps/docs/src/pages/component/[id].astro, apps/docs/src/storybook-loader.ts
=> fix: docs sidebar

package.json, pnpm-lock.yaml
resolves https://github.com/fractaldotbox/ddevkit/security/dependabot/46
=> fix: dependabot/46 by force elliptic >=6.6.1 

.changeset/config.json, .github/workflows/check.yml, .github/workflows/release.yml, .github/workflows/storybook.yml, biome.json
=> chore: remove draft workflows
